# Generated by Django 5.0.3 on 2024-04-04 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='creator',
        ),
        migrations.AddField(
            model_name='userimage',
            name='creator',
            field=models.ManyToManyField(related_name='image', to=settings.AUTH_USER_MODEL),
        ),
    ]
